/*
 * To change this license header, choose License Headers in Project Properties.
 * To change this template file, choose Tools | Templates
 * and open the template in the editor.
 */
package view;

import controle.EditalDAO;
import controle.MateriaDAO;
import java.awt.HeadlessException;
import java.sql.SQLException;
import java.util.ArrayList;
import java.util.List;
import java.util.logging.Level;
import java.util.logging.Logger;
import javax.swing.JOptionPane;
import model.Edital;
import model.Materia;

/**
 *
 * @author Dev-2810
 */
public final class MateriaCadastroTela extends javax.swing.JFrame {

 private final Materia materia = new Materia();
 
 private List<Edital> editais = new ArrayList<>();
 private final EditalDAO editalDAO = new EditalDAO();

    
    public MateriaCadastroTela() {
        initComponents();
        this.setLocationRelativeTo(null);
        preencherEdital();
    }
    
     public void preencherEdital(){
        
       // editais = new ArrayList<>();
       // editalDAO = new EditalDAO();
        try {          
           editais =  editalDAO.listar();
        } catch (Exception e) {
            JOptionPane.showMessageDialog(this,"Erro Registro!"+e);
        }
        comboEdital.removeAllItems();
        editais.forEach((edital) -> {
            comboEdital.addItem( edital.getNome()+"__"+edital.getCargo());
           
     }); /*
     List<String> sortEdital=new ArrayList();
     for(Edital edital: editais){
     sortEdital.add(edital.getNome());
     }
     for(String sorte: sortEdital){
     comboEdital.addItem(sorte);
     }*/
    }
    
   private void preencheDados(){
      materia.setNome(campoMateria.getText().toUpperCase());
      materia.setConhecimento((String) comboConhecimento.getSelectedItem());
      //Edital edital = new Edital();
      String nomeEdital = (String) comboEdital.getSelectedItem();
     
      int id=0;
       for (Edital e: editais) {
           
           if((e.getNome()+"__"+e.getCargo()).equals(nomeEdital)){
               id =  (int) e.getId();
               System.out.println("iddd"+ e.getId());
           }
           
       }
       try {
           materia.setEdital(editalDAO.buscarPorId(id));
       } catch (Exception e) {
           JOptionPane.showMessageDialog(this,"Erro Registro!"+e);
       }
      
      
     
   }
    
    private void inserirBD() throws SQLException, ClassNotFoundException{
        MateriaDAO dao = new MateriaDAO();
        try {
            if(dao.incluir(materia)){
                JOptionPane.showMessageDialog(this,"Registro salvo com sucesso!");
         
            }
        } catch (HeadlessException | SQLException e) {
            JOptionPane.showMessageDialog(this,"Erro Registro!"+e);
        }

    }
    

    private void limparcampo(){
        campoMateria.setText("");
        comboConhecimento.setSelectedIndex(0);
        comboEdital.setSelectedIndex(0);
    }
    
    private void salvar() throws SQLException, ClassNotFoundException{
            
              preencheDados();
             inserirBD();           
             limparcampo();
       
      
    }
    
    

    /**
     * This method is called from within the constructor to initialize the form.
     * WARNING: Do NOT modify this code. The content of this method is always
     * regenerated by the Form Editor.
     */
    @SuppressWarnings("unchecked")
    // <editor-fold defaultstate="collapsed" desc="Generated Code">//GEN-BEGIN:initComponents
    private void initComponents() {

        jPanel1 = new javax.swing.JPanel();
        jLabel1 = new javax.swing.JLabel();
        campoMateria = new javax.swing.JTextField();
        botaoSalvar = new javax.swing.JButton();
        jButton1 = new javax.swing.JButton();
        comboConhecimento = new javax.swing.JComboBox<>();
        jLabel2 = new javax.swing.JLabel();
        jLabel3 = new javax.swing.JLabel();
        comboEdital = new javax.swing.JComboBox<>();

        setDefaultCloseOperation(javax.swing.WindowConstants.DISPOSE_ON_CLOSE);
        setTitle("Cadastro de matéria");

        jPanel1.setBorder(javax.swing.BorderFactory.createTitledBorder("Cadastro de materia"));

        jLabel1.setText("Nome da materia");

        botaoSalvar.setText("Salvar");
        botaoSalvar.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                botaoSalvarActionPerformed(evt);
            }
        });

        jButton1.setText("Cancelar");
        jButton1.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                jButton1ActionPerformed(evt);
            }
        });

        comboConhecimento.setModel(new javax.swing.DefaultComboBoxModel<>(new String[] { "Básico", "Específico" }));

        jLabel2.setText("Conhecimento:");

        jLabel3.setText("Edital:");

        comboEdital.setModel(new javax.swing.DefaultComboBoxModel<>(new String[] { "Item 1", "Item 2", "Item 3", "Item 4" }));

        javax.swing.GroupLayout jPanel1Layout = new javax.swing.GroupLayout(jPanel1);
        jPanel1.setLayout(jPanel1Layout);
        jPanel1Layout.setHorizontalGroup(
            jPanel1Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(jPanel1Layout.createSequentialGroup()
                .addGroup(jPanel1Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                    .addGroup(jPanel1Layout.createSequentialGroup()
                        .addGap(82, 82, 82)
                        .addComponent(botaoSalvar)
                        .addGap(18, 18, 18)
                        .addComponent(jButton1))
                    .addGroup(jPanel1Layout.createSequentialGroup()
                        .addContainerGap()
                        .addGroup(jPanel1Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                            .addComponent(campoMateria, javax.swing.GroupLayout.PREFERRED_SIZE, 285, javax.swing.GroupLayout.PREFERRED_SIZE)
                            .addComponent(jLabel1)
                            .addGroup(jPanel1Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.TRAILING)
                                .addGroup(jPanel1Layout.createSequentialGroup()
                                    .addComponent(jLabel3)
                                    .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.UNRELATED)
                                    .addComponent(comboEdital, javax.swing.GroupLayout.PREFERRED_SIZE, 204, javax.swing.GroupLayout.PREFERRED_SIZE))
                                .addGroup(jPanel1Layout.createSequentialGroup()
                                    .addComponent(jLabel2)
                                    .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.UNRELATED)
                                    .addComponent(comboConhecimento, javax.swing.GroupLayout.PREFERRED_SIZE, 162, javax.swing.GroupLayout.PREFERRED_SIZE))))))
                .addContainerGap(19, Short.MAX_VALUE))
        );
        jPanel1Layout.setVerticalGroup(
            jPanel1Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(jPanel1Layout.createSequentialGroup()
                .addContainerGap()
                .addComponent(jLabel1)
                .addGap(3, 3, 3)
                .addComponent(campoMateria, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                .addGroup(jPanel1Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                    .addComponent(jLabel3)
                    .addComponent(comboEdital, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE))
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED, 17, Short.MAX_VALUE)
                .addGroup(jPanel1Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                    .addComponent(jLabel2)
                    .addComponent(comboConhecimento))
                .addGap(33, 33, 33)
                .addGroup(jPanel1Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                    .addComponent(botaoSalvar)
                    .addComponent(jButton1))
                .addGap(32, 32, 32))
        );

        javax.swing.GroupLayout layout = new javax.swing.GroupLayout(getContentPane());
        getContentPane().setLayout(layout);
        layout.setHorizontalGroup(
            layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(layout.createSequentialGroup()
                .addContainerGap()
                .addComponent(jPanel1, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)
                .addContainerGap(javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE))
        );
        layout.setVerticalGroup(
            layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(layout.createSequentialGroup()
                .addContainerGap()
                .addComponent(jPanel1, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
                .addContainerGap())
        );

        pack();
    }// </editor-fold>//GEN-END:initComponents

    private void botaoSalvarActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_botaoSalvarActionPerformed
 
     try {
         try {
             salvar();
         } catch (ClassNotFoundException ex) {
             Logger.getLogger(MateriaCadastroTela.class.getName()).log(Level.SEVERE, null, ex);
         }
     } catch (SQLException ex) {
         Logger.getLogger(MateriaCadastroTela.class.getName()).log(Level.SEVERE, null, ex);
     }
    }//GEN-LAST:event_botaoSalvarActionPerformed

    private void jButton1ActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_jButton1ActionPerformed
        new MateriaPesquisaTela().setVisible(true);
        dispose();
    }//GEN-LAST:event_jButton1ActionPerformed

    /**
     * @param args the command line arguments
     */
    public static void main(String args[]) {
              
        
        java.awt.EventQueue.invokeLater(() -> {
            new MateriaCadastroTela().setVisible(true);
        });
    }

    // Variables declaration - do not modify//GEN-BEGIN:variables
    private javax.swing.JButton botaoSalvar;
    private javax.swing.JTextField campoMateria;
    private javax.swing.JComboBox<String> comboConhecimento;
    private javax.swing.JComboBox<String> comboEdital;
    private javax.swing.JButton jButton1;
    private javax.swing.JLabel jLabel1;
    private javax.swing.JLabel jLabel2;
    private javax.swing.JLabel jLabel3;
    private javax.swing.JPanel jPanel1;
    // End of variables declaration//GEN-END:variables
}
